name: prun
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=2.307=netlib
  - blas-devel=3.11.0=7_netlib
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_4
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=7_hc00574d_netlib
  - libcblas=3.11.0=7_h8e06fc2_netlib
  - libdeflate=1.25=h17f619e_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgomp=15.2.0=he0feb66_14
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=7_h8876d29_netlib
  - liblapacke=3.11.0=7_hb041515_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libtiff=4.2.0=hf544144_3
  - libtmglib=3.11.0=7_h8876d29_netlib
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=20.1.8=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - mkl=2025.2.0=h901ac74_628
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - olefile=0.47=pyhd8ed1ab_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.3=hab00c5b_0_cpython
  - python_abi=3.12=8_cp312
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tbb=2022.1.0=h4ce085d_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - codecarbon==3.2.0
      - colorama==0.4.6
      - compressed-tensors==0.12.2
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - dataproperty==1.1.0
      - datasets==4.1.1
      - dill==0.4.0
      - evaluate==0.4.6
      - executing==2.2.1
      - fief-client==0.20.0
      - filelock==3.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - icecream==2.1.8
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonlines==4.0.0
      - jwcrypto==1.5.6
      - kiwisolver==1.4.9
      - llmcompressor==0.8.1
      - lm-eval==0.4.9.2
      - loguru==0.7.3
      - lorem==0.1.1
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.6
      - nltk==3.9.2
      - numexpr==2.14.1
      - numpy==2.3.3
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - pathvalidate==3.3.1
      - peft==0.18.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - portalocker==3.2.0
      - prettytable==3.17.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - questionary==2.1.1
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rouge-score==0.1.2
      - ruff==0.14.7
      - sacrebleu==2.5.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentence-transformers==5.1.2
      - sentry-sdk==2.46.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - sympy==1.14.0
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - transformers
      - triton==3.4.0
      - typepy==1.3.4
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.23.0
      - wcwidth==0.2.14
      - word2number==1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - yaspin==3.3.0
      - zstandard==0.25.0
prefix: /home/francescopio.monaco/.conda/envs/prun
